### PR TITLE
Improved hsm view

### PR DESCRIPTION
**Pull request by antarcticrainforest**
This does two things:

- It loads the slk module rather then using a fixed and outdated path to the slk binary
- It creates an (empty) xarray dataset only form the tags found in netcdf and netcdf_header metadata. Then at least some rudimentary overview of the meta-data can be displayed.

The output of a dataset that hasn't been tagged with the special string that is a json representation of the whole data set would look like this:

```
<Dataset>
Dimensions:  ()
Data variables:
    *empty*
Attributes: (12/50)
    Var_Long_Name:         time,Longitude,Latitude,pressure,Eastward Wind
    License:               CMIP6 model data produced by CSIRO is licensed und...
    Title:                 ACCESS-CM2 output prepared for CMIP6
    Var_Name:              time,time_bnds,lon,lon_bnds,lat,lat_bnds,plev,plev...
    Pid:                   hdl:21.14100/215c74d3-0509-4aca-8338-958b6c502eab
    Experiment_Id:         amip
    ...                    ...
    Parent_Experiment_Id:  no parent
    Activity_Id:           CMIP
    Frequency:             mon
    Sub_Experiment:        none
    Further_Info_Url:      https://furtherinfo.es-doc.org/CMIP6.CSIRO-ARCCSS....
    Variant_Label:         r1i1p1f1
```

I think I can't do really much more at the moment because essential information, like the dimensionality of the variables, are missing.

### CODE REVIEW

**Comment by antarcticrainforest** [comment]
I've slightly updated the displayed information by overriding the string representation for empty datasets. The cli output looks like this:

```
<Dataset (byte-size: unkown)>
Dimensions:  ()
Data variables:
    *not enough information for display*
Attributes:
    Var_Long_Name:         time,Longitude,Latitude,pressure,Eastward Wind
    License:               CMIP6 model data produced by CSIRO is licensed und...
    Title:                 ACCESS-CM2 output prepared for CMIP6
    Var_Name:              time,time_bnds,lon,lon_bnds,lat,lat_bnds,plev,plev...
    Pid:                   hdl:21.14100/215c74d3-0509-4aca-8338-958b6c502eab
    Experiment_Id:         amip
    Institution:           CSIRO (Commonwealth Scientific and Industrial Rese...
    Time_Min:              285336000000
    Source:                ACCESS-CM2 (2019):aerosol: UKCA-GLOMAP-modeatmos: ...
    Project:               CMIP6
    Institution_Id:        CSIRO-ARCCSS
    Var_Std_Name:          time,longitude,latitude,air_pressure,eastward_wind
    Creation_Date:         2019-11-08T09:29:03Z
    External_Description:  https://furtherinfo.es-doc.org/CMIP6.CSIRO-ARCCS
    Realm:                 atmos
    Time_Max:              311558400000
    Physics_Index:         1
    Tracking_Id:           hdl:21.14100/215c74d3-0509-4aca-8338-958b6c502eab
    Nominal_Resolution:    250 km
    Grid:                  native atmosphere N96 grid (144x192 latxlon)
    Product:               model-output
    Source_Id:             ACCESS-CM2
    Parent_Time_Units:     no parent
    Data_Specs_Version:    01.00.30
    Initialization_Index:  1
    Lon_Max:               180.0
    Parent_Variant_Label:  no parent
    Parent_Source_Id:      no parent
    Source_Type:           AGCM
    Table_Id:              Amon
    Level_Max:             100000.00000001001
    Parent_Activity_Id:    no parent
    Forcing_Index:         1
    Parent_Mip_Era:        no parent
    Lat_Min:               0.0
    Sub_Experiment_Id:     none
    Grid_Label:            gn
    Lon_Min:               101.25
    Experiment:            AMIP
    Level_Min:             100.00000001000001
    Lat_Max:               50.0
    Mip_Era:               CMIP6
    Variable_Id:           ua
    Realization_Index:     1
    Parent_Experiment_Id:  no parent
    Activity_Id:           CMIP
    Frequency:             mon
    Sub_Experiment:        none
    Further_Info_Url:      https://furtherinfo.es-doc.org/CMIP6.CSIRO-ARCCSS
    Variant_Label:         r1i1p1f1
```

But the HTML representation is not changed.

**Comment by antarcticrainforest** [comment]
The unkown byte-size botheres me, @Karinon how can I retrieve the file size from the metadata?

**Comment by Karinon** [comment]
You can either call `slk_helpers size <path>` which returns the size in bytes and nothing more, or you can call the `resources`-API-Endpoint which has a `size`-field in the output.  Don't use `slk list` for that as the output is truncated and you have to do much more parsing

**Comment by Karinon** [comment]
Output looks nice!
Just out of curiosity, what is your policy regarding the SLK authentication? Do you intend to refresh your token manually all 30 days or is there something more sophisticated in the background?

**Comment by antarcticrainforest** [comment]
> You can either call `slk_helpers size <path>` which returns the size in bytes and nothing more, or you can call the `resources`-API-Endpoint which has a `size`-field in the output. Don't use `slk list` for that as the output is truncated and you have to do much more parsing

Great, thanks for clarification

**Comment by antarcticrainforest** [comment]
> Output looks nice! Just out of curiosity, what is your policy regarding SLK authentication? Do you intend to refresh your token manually all 30 days or is there something more sophisticated in the background?

Indeed, there is something going on in the background. The code evaluates an environment variable, that can be passed by paramiko and holds a base64 encoded version of the user's password. If this variable is set then it will log on to the system by itself. The trick is that the freva web automatically base encodes the password and sets it as the magic paramiko env variable on ssh connections.

**Review by eelucio — APPROVED** [review]

**Comment by eelucio** [comment]
lgtm

**Review by Karinon — APPROVED** [review]
LGTM

**Pull request merged**
